smart119:
  uploadPath: c:/var/uploaded_files/
  username: admin
  password: 111111
  baiduMapApiKey: vU6GCDwes9ROs5r84QCBvCQEMRcCNOgn
  gaodeMapApiKey: 6abf4a07a2d27ca236c01b4be5341be9
logging:
  level:
    root: info
    com.bootdo: debug
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.40.1.161:3306/smart119_cs?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: abc@123
    #password: ENC(q3rJHyQxFAfpLHxLp89cAw==)
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    # 连接超时时间（毫秒）
    timeout: 10000ms
    jedis:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
  rabbitmq:
    host: 10.40.1.222
    mq.port: 5672
    mq.username: nationaleconomy
    mq.password: nationaleconomy
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: auto
        concurrency: 1
        max-concurrency: 1
        retry:
          enabled: true
ftp:
  ip: 10.40.1.222
  user: nationaleconomy
  password: abc123
  uploadFolder: dataImport

jasypt:
  encryptor:
    password: jasypt

appId:

#是否开启swagger文档
swagger:
  show: false

log:
  path: ../logs/
  level: info
