server:
  port: 8888
smart119:
  uploadPath: uploadFile/
  username: admin
  password: 111111
  baiduMapApiKey: vU6GCDwes9ROs5r84QCBvCQEMRcCNOgn
  gaodeMapApiKey: 6abf4a07a2d27ca236c01b4be5341be9
logging:
  level:
    root: info
    com.bootdo: debug
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sh-cynosdbmysql-grp-gbzklb7c.sql.tencentcdb.com:22075/springboot_demo
    username: wangguangyu
    password: wang@guang@yu1989
    #password: ENC(q3rJHyQxFAfpLHxLp89cAw==)
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true

jasypt:
  encryptor:
    password: jasypt


#是否开启swagger文档
swagger:
  show: false

#Shiro相关配置
security:
  shiro:
    globalSessionTimeout: 28800  # 登录过期时长8小时

log:
  path: ../logs/
  level: info

#mybatis
mybatis-plus:
  mapper-locations: classpath*:mybatis/**/*Mapper.xml
  type-handlers-package: com.smart119.common.handler
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

weixin:
  secret: b955358475bd81c90f166a4010c067a8
  appid: wx638e212bbba9e7f7
  env: prod-0gws2yp30d12fdb1
  url: https://api.weixin.qq.com/
