server:
  session-timeout: 100
spring:
  application:
    #用于nacos注册名
    name: smart119-backend
  thymeleaf:
    #mode: LEGACYHTML5
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: @profiles.active@
  servlet:
    multipart:
      enabled: true
      max-file-size: 300MB
      max-request-size: 300MB
  server:
    max-http-header-size: 4048576
    tomcat:
      max-http-post-size: -1  #请求参数长度
  devtools:
    restart:
      enabled: true
  cache:
    type:  ehcache
    ehcache:
      config: classpath:config/ehcache.xml

rsa-private: MIICeAIBADANBgkqhkiG9w0BAQEFAASCAmIwggJeAgEAAoGBAIwv99Dn7G94q2Y2sXGbzwKZsQu5nTSVImofPjqp/TsES+yvx32kiKI98FQVNihWPTcjAB5GVNxqvW5hO/9RXWy3YIEm4xjevSGc1f4HEsFFq+SgzVowryDWhahm9oyUXDwljVUZk+kM7ySIIQ0ns6iuRonUdNl3rRc90Wu1yEZXAgMBAAECgYA7drFgnK/uzLmvfq2f6h5SFQ1DUvV683OInj4QNkDjAryN5jXxdpQ6dZl2oRS64XHP7HnFXcHrSR+XLYl8kG/W5qMRuHpOk2Mgds++xtDKvTD2NS/6Mr2S0uXlEqtK8p0G2jQBXKryJiHIroyKiIz4e9tKqOwExFZiDydwAM8F+QJBANcXCaeHMHrTklzb4s3Ve+YdzBdarAlkRXbjhXFgRcx6TqX+zTR9SUrphHaI6PhLvy7nTlCWz2+IChJvTqcpx5sCQQCm2dd1hgnNn/HJUUqZOnUHoXCxZQ6CbSoRrD+OovqraJ0ezKrwIIjav6hC+txWA7MoM7ciX/+7oEXfkgtygi31AkEAkJz1qcR0LPDZBEP2vsudTP+Vu9IDvyDCr4eTrcG7zBojjOm+0F64C3zrycKNWHudJAzyk66B84v0saZSrIOjpwJBAJlXpdv9xy6yq50w19WBUyMjLRXr4Wze9QXu/y6Q/L3h1F0FDqjHzd70u6hrM2rd1Z7CALJX9gkzIGR7rYecuq0CQQDI2dr2rlKpf8ASaCbIRpfjMv1F3HfPLtufTQpsSWj8cGeQ+04LQTkCj6S7Mk0WYI8f8Z0+ietHqRM1+WHHiY2x
